env:
  node: true
  es2021: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
    - plugin:import/warnings
    - 'plugin:@typescript-eslint/recommended'

rules:
  linebreak-style: [error, unix]
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-var-requires': off

parserOptions:
  sourceType: module